participant_project/participant_app/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # search
    path('search/', views.search, name='search'),
    # index
    path('', views.index, name='index'),
    # family
    path('family/add/', views.add_family, name='add_family'),   
    path('family/<int:family_id>/', views.family_detail, name='family_detail'),
    path('family/<int:family_id>/update/', views.update_family, name='update_family'),
    path('family/<int:family_id>/delete/', views.delete_family, name='delete_family'),
    path('family/', views.family_query, name='family_query'),
    # adult
    path('adult/add/', views.add_adult, name='add_adult'),  
    path('adult/<int:adult_id>/', views.adult_detail, name='adult_detail'),
    path('adult/<int:adult_id>/update/', views.update_adult, name='update_adult'),
    path('adult/<int:adult_id>/delete/', views.delete_adult, name='delete_adult'),
    path('adult/', views.adult_query, name='adult_query'),

    # child
    path('child/add/', views.add_child, name='add_child'),  
    path('child/<int:child_id>/', views.child_detail, name='child_detail'),
    path('child/<int:child_id>/update/', views.update_child, name='update_child'),
    path('child/<int:child_id>/delete/', views.delete_child, name='delete_child'),
    path('child/', views.child_query, name='child_query'),
    
    # languages
    path('language/add/', views.add_language, name='add_language'),   

    # music
    path('musical_skill/add/', views.add_musical_skill, name='add_musical_skill'),   

    # assessments

    ## add assessment
    path('assessment/', views.assessment_list, name='assessment_list'),
    path('assessment/add/', views.add_assessment, name='add_assessment'),
    ## view assessment
    path('assessment/<str:assessment_name>/', views.assessment_detail, name='assessment_detail'),
    ## update assessment
    path('assessment/<str:assessment_name>/update/', views.update_assessment, name='update_assessment'),
    ## delete assessment
    path('assessment/<str:assessment_name>/delete/', views.delete_assessment, name='delete_assessment'),
    ## choose assessment to run
    path('assessment_run/add/', views.choose_assessment, name='choose_assessment'),
    ## add assessment run w/ preselected person
    path('assessment_run/add/<str:assessment_name>/<str:participant_type>/<int:participant>', views.add_assessment_run, name='add_assessment_run'),
    ## add assessment run
    path('assessment_run/add/<str:assessment_name>/<str:participant_type>/', views.add_assessment_run, name='add_assessment_run'),
    ## view assessment run detail
    path('assessment_run/<int:assessment_run_id>/', views.assessment_run_detail, name='assessment_run_detail'),
    ## delete assessment run
    path('assessment_run/<str:assessment_run_id>/delete/', views.delete_assessment_run, name='delete_assessment_run'),
    ## update assessment run
    path('assessment_run/<str:assessment_run_id>/update/', views.update_assessment_run, name='update_assessment_run'),

    # experiments
    path('experiment/', views.experiment_list, name='experiment_list'),
    path('experiment/add/', views.add_experiment, name='add_experiment'),
    path('experiment/<str:experiment_name>/', views.experiment_detail, name='experiment_detail'),
    path('experiment/<str:experiment_name>/sections/add/', views.add_experiment_section_fields, name='add_experiment_section_fields'),
    path('experiment/<str:experiment_name>/sections/update/', views.update_experiment_section_fields, name='update_experiment_section_fields'),

    path('experiment/<str:experiment_name>/update/', views.update_experiment, name='update_experiment'),
    path('experiment/<str:experiment_name>/delete/', views.delete_experiment, name='delete_experiment'),


    path('experiment/<str:experiment_name>/experiment_section/<str:experiment_section_name>/', views.experiment_section_detail, name='experiment_section_detail'),
    # path('experiment/<str:experiment_name>/experiment_section/<str:experiment_section_name>/update/', views.update_experiment_section, name='update_experiment_section'),
    path('experiment/<str:experiment_name>/experiment_section/<str:experiment_section_name>/delete/', views.delete_experiment_section, name='delete_experiment_section'),


    path('experiment_section_run/add/', views.choose_experiment_section, name='choose_experiment_section'),
    path('experiment_section_run/add/<str:experiment_name>/<str:experiment_section_name>/<str:participant_type>/<int:participant>', views.add_experiment_section_run, name='add_experiment_section_run'),
    path('experiment_section_run/add/<str:experiment_name>/<str:experiment_section_name>/<str:participant_type>/', views.add_experiment_section_run, name='add_experiment_section_run'),
    path('experiment_section_run/<int:experiment_section_run_id>/', views.experiment_section_run_detail, name='experiment_section_run_detail'),

    path('experiment_section_run/<int:experiment_section_run_id>/delete/', views.delete_experiment_section_run, name='delete_experiment_section_run'),
    path('experiment_section_run/<int:experiment_section_run_id>/update/', views.update_experiment_section_run, name='update_experiment_section_run'),
]

    

participant_project/participant_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('participant_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('select2/', include('django_select2.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

participant_project/participant_app/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse
from django.contrib.auth.models import Group, User



class Language(models.Model):
    class Meta:
        verbose_name = "Language"
        verbose_name_plural = "Languages"
        ordering = ['language_name']
    language_name = models.CharField("Language Name", max_length = 100, primary_key = True)
    def __str__(self):
        return '%s' % (self.language_name) 

class MusicalSkill(models.Model):
    class Meta:
        verbose_name = "Musical Skill"
        verbose_name_plural = "Musical Skills"
        ordering = ['skill']
    skill = models.CharField('Skill', max_length = 100, primary_key = True)
    def __str__(self):
        return '%s' % (self.skill) 

class Lab(models.Model):
    class Meta:
        verbose_name = "Lab"
        verbose_name_plural = "Labs"
        ordering = ['lab_name']
    lab_name = models.CharField(max_length = 100, primary_key = True)
    group = models.ForeignKey(Group, null= True, blank= True, on_delete = models.SET_NULL)
    def __str__(self):
        return '%s' % (self.lab_name) 

class Person(models.Model):
    id = models.IntegerField(primary_key = True, verbose_name = "ID")
    given_name = models.CharField(max_length = 100, verbose_name = "Given Name")
    preferred_name = models.CharField(max_length = 100, blank = True, null = True, verbose_name = "Preferred Name")
    surname = models.CharField(max_length = 100, default='', verbose_name = "Surname")
    birth_date = models.DateField(verbose_name = "Birth Date")
    gender = models.CharField(max_length = 100, default='')
    health_notes = models.TextField(max_length=1000, blank = True, null = True, verbose_name = "Health Notes")
    personal_notes = models.TextField(max_length=1000, blank = True, null = True, verbose_name="Personal Notes")
    def __str__(self):
        return '%s: %s %s' % (self.id, self.given_name, self.surname) 

    class Meta:
        abstract = True
    
class Adult(Person):
    class Meta:
        verbose_name = "Adult"
        verbose_name_plural = "Adults"
        ordering = ['id']
    sfu_id = models.IntegerField(blank = True, null = True, verbose_name = "SFU ID")
    address = models.CharField(max_length=200, blank = True, null = True)
    years_of_education = models.IntegerField(
        blank = True,
        null = True,
        validators=[
            MinValueValidator(0), 
            MaxValueValidator(20),
        ],
        verbose_name = "Years of Education"
    )
    phone = models.CharField(max_length=50, blank = True, null = True)
    email = models.EmailField(blank = True, null = True)

    CONTACT_CHOICES = (
        ('P', 'Phone'),
        ('E', 'Email'),
    )
    contact_pref = models.CharField(max_length=1, choices = CONTACT_CHOICES, verbose_name = "Contact Preference", blank = True, null = True)    

    PHONETIME_CHOICES = (
        ('WDM', 'Weekday Mornings'),
        ('WDA', 'Weekday Afternoons'),
        ('WDE', 'Weekday Evenings'),
        ('WEM', 'Weekend Mornings'),
        ('WEA', 'Weekend Afternoons'),
        ('WEE', 'Weekend Evenings'),
        ('ANY', 'Anytime'),
        ('DNC', 'Do Not Call'),
    )
    pref_phone_time = models.CharField(max_length = 3, choices = PHONETIME_CHOICES, verbose_name = "Preferred Phone Time", blank = True, null = True)
    
    languages = models.ManyToManyField('Language', blank = True, through='Speaks', related_name = 'speaks')
    musical_background = models.ManyToManyField('MusicalSkill', blank = True, through='MusicalExperience')


class Child(Person):
    class Meta:
        verbose_name = "Child"
        verbose_name_plural = "Children"
        ordering = ['id']
    gestation_length_weeks = models.SmallIntegerField(blank = True, null = True, verbose_name = "Gestation Length (Weeks)")
    was_full_term = models.BooleanField(blank = True, null = True, verbose_name = "Was Full Term?")
    birth_weight = models.SmallIntegerField(blank = True, null = True, verbose_name = "Birth Weight (Grams)")
    birth_height = models.SmallIntegerField(blank = True, null = True, verbose_name = "Birth Height (CM)")
    hx_repeated_ear_infection = models.TextField(max_length=1000, blank = True, null = True, verbose_name = "HX of Repeated Ear Infection")
    hereditary_audio_problems = models.BooleanField(verbose_name = "Hereditary Audio Problems?")
    hereditary_language_pathologies = models.BooleanField(verbose_name = "Hereditary Language Pathologies?")
    exposed_to = models.ManyToManyField('Language', through='IsExposedTo', default = None, verbose_name = "Languages Exposed To")

class Family(models.Model):
    class Meta:
        verbose_name = "Family"
        verbose_name_plural = "Families"
        ordering = ['id']
    id = models.IntegerField(primary_key = True, verbose_name = "ID")
    parents = models.ManyToManyField('Adult', through='IsParentIn')
    children = models.ManyToManyField('Child', through='IsChildIn')
    notes = models.TextField(max_length=1000, blank = True, null = True, verbose_name = "Notes")
    def __str__(self):
        return 'Family # %s' % (self.id) 

class Experiment(models.Model):
    class Meta:
        ordering = ['experiment_name']
    experiment_name = models.CharField('Experiment Name', max_length = 100, primary_key = True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('prep', 'In Prep'),
        ('recruiting', 'Actively Recruiting'),
        ('inactive', 'Inactive'),
    )
    status = models.CharField(max_length = 10, choices = STATUS_CHOICES)
    def __str__(self):
        return '%s' % (self.experiment_name) 

class Experiment_Section(models.Model):
    class Meta:
        verbose_name = "Experiment Section"
        verbose_name_plural = "Experiment Sections"
        ordering = ['experiment_section_name']
    experiment_section_name = models.CharField(max_length = 100)
    experiment = models.ForeignKey(Experiment, on_delete=models.CASCADE)
    STATUS_CHOICES = (
        ('prep', 'In Prep'),
        ('recruiting', 'Actively Recruiting'),
        ('inactive', 'Inactive'),
    )
    section_status = models.CharField(max_length = 10, choices = STATUS_CHOICES)

    def __str__(self):
        return '%s: %s' % (self.experiment, self.experiment_section_name) 

class Experiment_Section_Run(models.Model):
    class Meta:
        verbose_name = "Experiment Section Run"
        verbose_name_plural = "Experiment Section Runs"
        ordering = ['experiment_section', 'participantAdult', 'participantChild']
    participantAdult = models.ForeignKey(Adult, verbose_name='Adult Participant', on_delete = models.CASCADE, null=True, blank=True)
    participantChild = models.ForeignKey(Child, verbose_name='Child Participant', on_delete = models.CASCADE, null=True, blank=True)
    experiment_section = models.ForeignKey(Experiment_Section, on_delete = models.CASCADE)
    date = models.DateField()
    notes = models.TextField(max_length=1000, null=True, blank=True)
    assessor = models.ForeignKey(User, null= True, blank= True, on_delete = models.SET_NULL)

class Experiment_Section_Field(models.Model):
    class Meta:
        verbose_name = "Experiment Section Field"
        verbose_name_plural = "Experiment Section Fields"
        ordering = ['field_name']
    field_name = models.CharField(max_length = 100, verbose_name = "Field Name")
    field_of = models.ForeignKey(Experiment_Section, on_delete = models.CASCADE)
    TYPE_OPTIONS = (
        ('Numeric', 'Numeric'),
        ('Pass/Fail', 'Pass/Fail'),
        ('Text', 'Text'),
    )
    type = models.CharField(max_length = 9, choices = TYPE_OPTIONS)
    def __str__(self):
        return '%s field %s for %s' % (self.type, self.field_name, self.field_of)

class Experiment_Section_Run_Field_Score(models.Model):
    experiment_section_run = models.ForeignKey(Experiment_Section_Run, on_delete = models.CASCADE)
    experiment_section_field = models.ForeignKey(Experiment_Section_Field, on_delete = models.CASCADE)
    score = models.CharField(max_length=100) 
    def __str__(self):
        return 'Score of [%s] for field [%s] of run [%s]' % (self.score, self.experiment_section_field, self.experiment_section_run)

class Assessment(models.Model):
    class Meta:
        ordering = ['assessment_name']
    assessment_name = models.CharField('Assessment Name', max_length = 100, primary_key = True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE)

    def __str__(self):
        return '%s' % (self.assessment_name) 


class Assessment_Run(models.Model):
    class Meta:
        verbose_name = "Assessment Run"
        verbose_name_plural = "Assessment Runs"
        ordering = ['participantAdult', 'participantChild']
    participantAdult = models.ForeignKey(Adult, verbose_name='Adult Participant', on_delete = models.CASCADE, null=True, blank=True)
    participantChild = models.ForeignKey(Child, verbose_name='Child Participant', on_delete = models.CASCADE, null=True, blank=True)
    assessment = models.ForeignKey(Assessment, on_delete = models.CASCADE, related_name="assessment_ran")

    date = models.DateField()
    notes = models.TextField(max_length=1000, null= True, blank= True)
    assessor = models.ForeignKey(User, null= True, blank= True, on_delete = models.SET_NULL)
    
    def __str__(self):
        return '%s took %s' % (self.participantAdult or self.participantChild, self.assessment)

class Assessment_Field(models.Model):
    class Meta:
        verbose_name = "Assessment Field"
        verbose_name_plural = "Assessment Fields"
    field_name = models.CharField(max_length = 100, verbose_name = "Field Name")
    field_of = models.ForeignKey(Assessment, on_delete = models.CASCADE)
    TYPE_OPTIONS = (
        ('Numeric', 'Numeric'),
        ('Pass/Fail', 'Pass/Fail'),
        ('Text', 'Text'),
    )
    type = models.CharField(max_length = 9, choices = TYPE_OPTIONS)
    def __str__(self):

participant_project/templates/participant_app/Family/list.html
{% extends "participant_app/nav.html" %}
{% block extraHead %}
    <title>Family Query - participant_app</title>
    {% load static %}
    {{ familyFilter.form.media.css }}
    <script src="{% static 'js/query.js' %}"></script>
    <script src="{% static 'js/date_warning.js' %}"></script>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <ul class="nav nav-tabs mb-4">
                <li class="nav-item"><a class="nav-link" href="{% url 'adult_query' %}">Adult</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'child_query' %}">Child</a></li>
                <li class="nav-item"><a class="nav-link active" href="{% url 'family_query' %}">Family</a></li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-12 mb-0">
                            Family Query
                            <div class="btn-group float-right"> 
                                <button class="btn btn-outline-light" type="button" data-toggle="collapse" data-target=".query-form" aria-controls="personalTable">
                                Expand/Collapse
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body query-form collapse show"> 
                    <form method="get" action="">
                        <div class="form-row">
                            <div class="col-md-12">
                                <h4>General</h4>
                            </div>
                        </div>
                        <div class="form-row mb-4">
                            <div class="col-md-12 form-group">
                                {{ familyFilter.form.notes_inc|as_crispy_field}}
                            </div>
                        </div> 
                        <div class="form-row">
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <h4>Parental Info</h4>
                                    </div>
                                </div>
                                <div class="form-row mb-4">
                                    <div class="col-md-6 form-group">
                                        {{ familyFilter.form.parent_given_name|as_crispy_field }}
                                    </div>
                                    <div class="col-md-6 form-group">
                                        {{ familyFilter.form.parent_surname|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-row">
                                    <div class="col-md-12">
                                        <h4>Child Info</h4>
                                    </div>
                                </div>
                                <div class="form-row mb-4">
                                    <div class="col-md-6 form-group">
                                        {{ familyFilter.form.child_given_name|as_crispy_field }}
                                    </div>
                                    <div class="col-md-6 form-group">
                                        {{ familyFilter.form.child_surname|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                        <div class="row">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-outline-dark">Query</button>
                                <a href="{% url 'family_query' %}" class="btn btn-outline-dark" role="button">Clear</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% comment %} </div> {% endcomment %}
    <div class="row">
        <div class="col-xl-12">
            <div class="card mb-4">
                <div class="card-header">
                    Results
                </div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr class="noTopBorder centeredCell">
                                <th>ID</th>
                                <th>Notes</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if familyFilter.qs.count %}
                                {% for family in familyFilter.qs%}
                                {% comment %} {% for adult in combined %} {% endcomment %}
                                    <tr class="centeredCell">
                                        <td>
                                            {{family.id}}
                                        </td>
                                        <td>
                                            {{family.notes}}
                                        </td>
                                        <td>
                                            <div class="btn-group">
                                                <a href="{% url 'family_detail' family_id=family.id %}" class="btn btn-outline-dark btn-sm" role="button">Open</a>
                                                <a href="{% url 'update_family' family_id=family.id %}" class="btn btn-outline-dark btn-sm" role="button">Update</a>
                                                <a href="{% url 'delete_family'  family_id=family.id %}" class="btn btn-outline-danger btn-sm" role="button">Delete</a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                            {% else%}
                                <tr class="centeredCell">
                                    <td colspan='8'>
                                        Sorry, no results.
                                    </tr>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
  
    {{ familyFilter.form.media.js }}  
{% endblock %}

participant_project/templates/participant_app/Family/new.html
{% extends "participant_app/nav.html" %}
{% load static %}
{% block extraHead %}
    <title>Add Family - participant_app</title>
    {{ parent_forms.media.css }}
    <script src="{% static 'js/family.js' %}"></script>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>New Family</h1>
    <form method="post" class="noBottomMargin">
    
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4">
                            <div class="card-header">
                                Basic Info
                            </div>
                            <div class="card-body">
                                {{family_form.id|as_crispy_field}}
                                {{family_form.notes|as_crispy_field}}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card mb-4">
                            <div class="table-responsive">
                                {{ parent_forms.management_form|crispy}}
                                <table class="table table-hover">
                                    <thead class="card-header">
                                        <tr class="noTopBorder">
                                            <td>
                                                Parent(s)
                                            </td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for parent_form in parent_forms %}
                                            <tr>
                                                <td>
                                                    {{parent_form.parent|as_crispy_field}}
                                                    {{parent_form.isPrimary|as_crispy_field}}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card mb-4">
                    <div class="table-responsive">
                        {{ child_forms.management_form|crispy}}
                        <table class="table table-hover">
                            <thead class="card-header">
                                <tr class="noTopBorder">
                                    <td>
                                        Child(ren)
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for child_form in child_forms %}
                                    <tr>
                                        <td>
                                            {{child_form.child|as_crispy_field}}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>



        <div class="btn-group"> 
            <input type="submit" class="btn btn-outline-dark" name="save" value="Save">
            <input type="submit" class="btn btn-outline-dark" name="save_add_another" value="Save & Add Another">
        </div>
    </form>
    {{ parent_forms.media.js}}
{% endblock %}

participant_project/templates/participant_app/Family/view.html
{% extends "participant_app/nav.html" %}

{% block extraHead %}
    <title>Family #{{family.id}} - participant_app</title>
{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h1>
                Family # {{family.id}}
            </h1>
        </div>
        <div class="col-md-4">
            <div class="btn-group float-right">
                <a href="{% url 'update_family' family_id=family.id %}" class="btn btn-outline-dark" role="button">Update</a>
                <a href="{% url 'delete_family' family_id=family.id %}" class="btn btn-outline-danger" role="button">Delete</a>
                
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="card mb-4">
                <div class="card-header">
                    Family Info
                </div>
                <div>
                    {% comment %} <h2>Personal Info</h2>         {% endcomment %}
                    <div id="personalTable" class="table-responsive">
                        <table class="table table-hover">
                            <tbody>
                                <tr class="noTopBorder">
                                
                                    <th>Primary Contact</th>
                                    <td>
                                        {% for parent in parents %}
                                            {% if parent.isPrimary %}
                                                <b>{{ parent.parent.given_name }}
                                                {{adult.preferred_name}}
                                                {{ parent.parent.surname }}
                                                by {{parent.parent.get_contact_pref_display}}</b><br>
                                                Email: {{ parent.parent.email}}<br>
                                                Phone: {{ parent.parent.phone}}
                                                ({{parent.parent.get_pref_phone_time_display}})
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                </tr>
                                <tr>
                                    <th>Notes</th>
                                    <td>{{family.notes}}</td>
                                </tr> 
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <h2>Parents</h2>
    {% for parent in parents %}
            {% with parent.parent as adult and parent.parent.id as testID %}
                {% load family_tags %}
                {% with parentsSpeak|hashval:testID as speaksLanguages and parentsMusic|hashval:testID as musical_exps %}
                    {% include "participant_app/Adult/_partial.html" %}
                {% endwith %}
            {% endwith %}
    {% endfor %}
    <h2>Children</h2>
    {% for kid in children %}
            {% with kid.child as child and kid.child.id as testID %}
                {% load family_tags %}
                {% with childrenLangExposure|hashval:testID as languages_exposed_to %}
                    {% include "participant_app/Child/_partial.html" %}
                {% endwith %}
            {% endwith %}
    {% endfor %}
    {% comment %} <h3>Children</h3>
    {% for child in children %}
        {{child.child.id}}, {{child.child.given_name}} {{child.child.surname}} 
        <a href="{% url 'child_detail' child_id=child.child.id %}">Update</a>
        <a href="{% url 'update_child' child_id=child.child.id %}">Edit</a><br>
    {% endfor %} {% endcomment %}
{% endblock %}